import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val android_arch_lifecycle_compiler: String = "android.arch.lifecycle:compiler:" +
            Versions.android_arch_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val android_arch_lifecycle_extensions: String = "android.arch.lifecycle:extensions:" +
            Versions.android_arch_lifecycle

    /**
     * https://developer.android.com/topic/libraries/architecture/index.html
     */
    const val work_runtime: String = "android.arch.work:work-runtime:" + Versions.work_runtime

    const val commons: String = "com.afollestad.material-dialogs:commons:" + Versions.commons

    /**
     * https://developer.android.com/testing
     */
    const val espresso_contrib: String = "com.android.support.test.espresso:espresso-contrib:" +
            Versions.com_android_support_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "com.android.support.test.espresso:espresso-core:" +
            Versions.com_android_support_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_intents: String = "com.android.support.test.espresso:espresso-intents:" +
            Versions.com_android_support_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val com_android_support_test_rules: String = "com.android.support.test:rules:" +
            Versions.com_android_support_test

    /**
     * https://developer.android.com/testing
     */
    const val com_android_support_test_runner: String = "com.android.support.test:runner:" +
            Versions.com_android_support_test

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val design: String = "com.android.support:design:" + Versions.design

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val gridlayout_v7: String = "com.android.support:gridlayout-v7:" + Versions.gridlayout_v7

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val mediarouter_v7: String = "com.android.support:mediarouter-v7:" +
            Versions.mediarouter_v7

    const val multidex_instrumentation: String = "com.android.support:multidex-instrumentation:" +
            Versions.multidex_instrumentation

    const val multidex: String = "com.android.support:multidex:" + Versions.multidex

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val preference_v14: String = "com.android.support:preference-v14:" +
            Versions.preference_v14

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val recyclerview_v7: String = "com.android.support:recyclerview-v7:" +
            Versions.recyclerview_v7

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val support_v4: String = "com.android.support:support-v4:" + Versions.support_v4

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * http://github.com/KeepSafe/dexcount-gradle-plugin/
     */
    const val dexcount_gradle_plugin: String = "com.getkeepsafe.dexcount:dexcount-gradle-plugin:" +
            Versions.dexcount_gradle_plugin

    /**
     * https://github.com/msdx/ViewPagerIndicator/tree/msdx
     */
    const val viewpagerindicator: String = "com.githang:viewpagerindicator:" +
            Versions.viewpagerindicator

    /**
     * https://github.com/AntennaPod/AntennaPod-AudioPlayer
     */
    const val antennapod_audioplayer: String = "com.github.AntennaPod:AntennaPod-AudioPlayer:" +
            Versions.antennapod_audioplayer

    /**
     * https://github.com/ByteHamster/SearchPreference
     */
    const val searchpreference: String = "com.github.ByteHamster:SearchPreference:" +
            Versions.searchpreference

    /**
     * https://github.com/bumptech/glide
     */
    const val com_github_bumptech_glide_compiler: String = "com.github.bumptech.glide:compiler:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/bumptech/glide
     */
    const val glide: String = "com.github.bumptech.glide:glide:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/bumptech/glide
     */
    const val okhttp3_integration: String = "com.github.bumptech.glide:okhttp3-integration:" +
            Versions.com_github_bumptech_glide

    const val fyydlin: String = "com.github.mfietz:fyydlin:" + Versions.fyydlin

    /**
     * https://github.com/shts/TriangleLabelView
     */
    const val trianglelabelview: String = "com.github.shts:TriangleLabelView:" +
            Versions.trianglelabelview

    const val com_github_triplet_play_gradle_plugin: String =
            "com.github.triplet.play:com.github.triplet.play.gradle.plugin:" +
            Versions.com_github_triplet_play_gradle_plugin

    const val exoplayer: String = "com.google.android.exoplayer:exoplayer:" + Versions.exoplayer

    const val play_services_cast: String = "com.google.android.gms:play-services-cast:" +
            Versions.play_services_cast

    /**
     * https://github.com/googlecast/CastCompanionLibrary-android
     */
    const val com_google_android_libraries_cast_companionlibrary_ccl: String =
            "com.google.android.libraries.cast.companionlibrary:ccl:" +
            Versions.com_google_android_libraries_cast_companionlibrary_ccl

    /**
     * https://developer.android.com/wear
     */
    const val com_google_android_support_wearable: String = "com.google.android.support:wearable:" +
            Versions.com_google_android_support_wearable

    const val com_google_android_wearable_wearable: String =
            "com.google.android.wearable:wearable:" + Versions.com_google_android_wearable_wearable

    /**
     * http://www.robotium.org/
     */
    const val robotium_solo: String = "com.jayway.android.robotium:robotium-solo:" +
            Versions.robotium_solo

    /**
     * https://github.com/JoanZapata/android-iconify/
     */
    const val android_iconify_fontawesome: String =
            "com.joanzapata.iconify:android-iconify-fontawesome:" + Versions.com_joanzapata_iconify

    /**
     * https://github.com/JoanZapata/android-iconify/
     */
    const val android_iconify_material: String =
            "com.joanzapata.iconify:android-iconify-material:" + Versions.com_joanzapata_iconify

    /**
     * https://github.com/leinardi/FloatingActionButtonSpeedDial
     */
    const val speed_dial: String = "com.leinardi.android:speed-dial:" + Versions.speed_dial

    const val nanohttpd_webserver: String = "com.nanohttpd:nanohttpd-webserver:" +
            Versions.nanohttpd_webserver

    /**
     * https://github.com/square/okhttp
     */
    const val okhttp_urlconnection: String = "com.squareup.okhttp3:okhttp-urlconnection:" +
            Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okhttp
     */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

    /**
     * https://github.com/square/okio/
     */
    const val okio: String = "com.squareup.okio:okio:" + Versions.okio

    /**
     * https://github.com/yqritc/RecyclerView-FlexibleDivider
     */
    const val recyclerview_flexibledivider: String = "com.yqritc:recyclerview-flexibledivider:" +
            Versions.recyclerview_flexibledivider

    /**
     * http://commons.apache.org/proper/commons-io/
     */
    const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/ReactiveX/RxAndroid
     */
    const val rxandroid: String = "io.reactivex.rxjava2:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxJava
     */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * http://commons.apache.org/proper/commons-lang/
     */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * http://commons.apache.org/proper/commons-text
     */
    const val commons_text: String = "org.apache.commons:commons-text:" + Versions.commons_text

    /**
     * http://awaitility.org
     */
    const val awaitility: String = "org.awaitility:awaitility:" + Versions.awaitility

    /**
     * http://greenrobot.org/eventbus/
     */
    const val eventbus_annotation_processor: String =
            "org.greenrobot:eventbus-annotation-processor:" + Versions.org_greenrobot

    /**
     * http://greenrobot.org/eventbus/
     */
    const val eventbus: String = "org.greenrobot:eventbus:" + Versions.org_greenrobot

    /**
     * https://jsoup.org/
     */
    const val jsoup: String = "org.jsoup:jsoup:" + Versions.jsoup

    /**
     * https://github.com/mockito/mockito
     */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core
}
