import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val android_arch_lifecycle: String = "1.1.1"

    const val work_runtime: String = "1.0.1"

    const val commons: String = "0.9.0.2" // available: "0.9.6.0"

    const val com_android_support_test_espresso: String = "3.0.2"

    const val com_android_support_test: String = "1.0.2"

    const val appcompat_v7: String = "27.1.1" // available: "28.0.0"

    const val design: String = "27.1.1" // available: "28.0.0"

    const val gridlayout_v7: String = "27.1.1" // available: "28.0.0"

    const val mediarouter_v7: String = "27.1.1" // available: "28.0.0"

    const val multidex_instrumentation: String = "1.0.2" // available: "1.0.3"

    const val multidex: String = "1.0.2" // available: "1.0.3"

    const val preference_v14: String = "27.1.1" // available: "28.0.0"

    const val recyclerview_v7: String = "27.1.1" // available: "28.0.0"

    const val support_v4: String = "27.1.1" // available: "28.0.0"

    const val com_android_tools_build_gradle: String = "3.5.0"

    const val lint_gradle: String = "26.5.0"

    const val dexcount_gradle_plugin: String = "0.8.5" // available: "0.8.6"

    const val viewpagerindicator: String = "2.5.1"

    const val antennapod_audioplayer: String = "v1.0.17" // available: "1.0.17"

    const val searchpreference: String = "v1.2.6" // available: "1.2.5"

    const val com_github_bumptech_glide: String = "4.8.0" // available: "4.9.0"

    const val fyydlin: String = "v0.4.2" // available: "0.4.2"

    const val trianglelabelview: String = "1.1.2"

    const val com_github_triplet_play_gradle_plugin: String = "2.3.0"

    const val exoplayer: String = "2.9.3" // available: "2.10.4"

    const val play_services_cast: String = "8.4.0" // available: "17.0.0"

    const val com_google_android_libraries_cast_companionlibrary_ccl: String = "2.9.1"

    const val com_google_android_support_wearable: String = "2.2.0" // available: "2.4.0"

    const val com_google_android_wearable_wearable: String = "2.2.0" // available: "2.4.0"

    const val robotium_solo: String = "5.6.3"

    const val com_joanzapata_iconify: String = "2.2.2"

    const val speed_dial: String = "1.0.2" // available: "3.0.0"

    const val nanohttpd_webserver: String = "2.1.1" // available: "2.2.0"

    const val com_squareup_okhttp3: String = "3.9.0" // available: "4.1.0"

    const val okio: String = "1.14.0" // available: "2.3.0"

    const val recyclerview_flexibledivider: String = "1.4.0"

    const val commons_io: String = "2.5" // available: "2.6"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

    const val rxandroid: String = "2.1.0" // available: "2.1.1"

    const val rxjava: String = "2.2.2" // available: "2.2.11"

    const val junit: String = "4.12"

    const val commons_lang3: String = "3.6" // available: "3.9"

    const val commons_text: String = "1.3" // available: "1.7"

    const val awaitility: String = "3.1.2" // available: "3.1.6"

    const val org_greenrobot: String = "3.1.1"

    const val jsoup: String = "1.11.2" // available: "1.12.1"

    const val mockito_core: String = "1.10.19" // available: "3.0.0"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6"

    const val gradleCurrentVersion: String = "5.4.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
