blank_issues_enabled: false
contact_links:
  - name: Help & Support
    url: https://forum.antennapod.org/
    about: Reduce developer's support workload by asking other users on our forum.
  - name: F-Droid Release
    url: https://antennapod.org/documentation/general/f-droid
    about: Waiting for an update to appear on F-Droid? No need to create an issue, please just be patient!
