name: Close issue/PR if no reply
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          days-before-stale: 7
          days-before-close: 7
          only-labels: 'Awaiting reply'
          stale-issue-label: 'Still awaiting reply'
          stale-pr-label: 'Still awaiting reply'
          stale-issue-message: "This issue will be closed when we don't get a reply within 7 days."
          stale-pr-message: "This PR will be closed when we don't get a reply within 7 days."
          labels-to-remove-when-unstale: 'Awaiting reply'
          close-issue-label: "Close reason: no reply"
          close-pr-label: "Close reason: no reply"
          close-issue-message: "This issue was closed because we didn't get a reply for 14 days."
          close-pr-message: "This PR was closed because we didn't get a reply for 14 days."
