name: Close issue/PR if no reply
on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          days-before-stale: 10
          days-before-close: 10
          only-labels: 'Awaiting reply'
          stale-issue-label: 'Still awaiting reply'
          stale-pr-label: 'Still awaiting reply'
          labels-to-remove-when-unstale: 'Awaiting reply'
          close-issue-label: "Close reason: no reply"
          close-pr-label: "Close reason: no reply"
          close-issue-message: "This issue was closed because we didn't get a reply for 20 days."
          close-pr-message: "This pr was closed because we didn't get a reply for 20 days."
